services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
  db:
    image: mysql:8.0.30
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword123
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=mypassword123
  api:
    build: ./api
    ports:
      - "4000:5000"
    volumes:
      - ./api:/api
volumes:
  db_data: